// Xybots core PLL wrapper (megafunction-style top, as generated by Altera PLL
// v17.0 and then hand-edited — see rtl/pll/pll_0002.v for the parameters and
// the counter derivation).
//
//   refclk   = CLK_50M (50 MHz)
//   outclk_0 = clk_sys   57.272727 MHz  (= 4 x 14.318181 MHz, SP-313 sheet 4)
//   outclk_1 = clk_sdram 57.272727 MHz, phase-shifted for the SDRAM_CLK pin
//              (+13095 ps = tap 66 = 270 deg, swept on hardware)

`timescale 1 ps / 1 ps
module pll (
		input  wire  refclk,   //  refclk.clk
		input  wire  rst,      //   reset.reset
		output wire  outclk_0, // outclk0.clk  clk_sys
		output wire  outclk_1, // outclk1.clk  SDRAM clock (phase-shifted)
		output wire  locked    //  locked.export
	);

	pll_0002 pll_inst (
		.refclk   (refclk),   //  refclk.clk
		.rst      (rst),      //   reset.reset
		.outclk_0 (outclk_0), // outclk0.clk
		.outclk_1 (outclk_1), // outclk1.clk
		.locked   (locked)    //  locked.export
	);

endmodule
